"""add class_date

Revision ID: 770570eac5f6
Revises: 
Create Date: 2025-04-01 17:13:00.841794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '770570eac5f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_column('class_date')

    # ### end Alembic commands ###
